---
- name: "install and start nginx"
  hosts: web
  become: true

  tasks:
    - name: "install nginx"
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: "start nginx"
      service:
        name: nginx
        state: started
        enabled: yes

    - name: "create index.html"
      copy:
        dest: /var/www/html/index.html
        content: "<h1>Welcome to the Web Server!</h1>"